version: "3"

networks:
    application:
        driver: bridge

services:

    nginx:
        image: 'nginx:alpine'
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - './:/var/www/html'
            - './docker-compose/nginx:/etc/nginx/conf.d/'
        networks:
            - application
        depends_on:
            - users
            - notifications

    users:
        build:
            context: ./users/
            dockerfile: Dockerfile
            args:
                user: 'laravel'
                uid: 1000
        image: users
        restart: unless-stopped
        working_dir: /var/www/html/users
        volumes:
            - './users:/var/www/html/users'
        networks:
            - application
        depends_on:
            - mysql

    notifications:
        build:
            context: ./notifications/
            dockerfile: Dockerfile
            args:
                user: 'laravel'
                uid: 1000
        image: notifications
        restart: unless-stopped
        working_dir: /var/www/html/notifications
        volumes:
            - './notifications:/var/www/html/notifications'
        networks:
            - application

    mysql:
        image: 'mysql:8.0'
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        ports:
            - "3306:3306"
        volumes:
            - 'db_data:/var/lib/mysql'
            - './docker-compose/mysql:/docker-entrypoint-initdb.d'
        networks:
            - application

    notifications-mq:
        build:
            context: ./notifications/
            dockerfile: Dockerfile
            args:
                user: 'laravel'
                uid: 1000
        image: notifications-mq
        restart: unless-stopped
        working_dir: /var/www/html/notifications
        volumes:
            - './notifications:/var/www/html/notifications'
        entrypoint: ['php', 'artisan', 'mq:consume']
        depends_on:
            - notifications
        networks:
            - application
volumes:
    db_data:
