version: "3"

networks:
    users:
        driver: bridge

services:

    nginx:
        image: 'nginx:alpine'
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - './:/var/www/html'
            - './docker-compose/nginx:/etc/nginx/conf.d/'
        networks:
            - users

    app:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                user: 'laravel'
                uid: 1000
        image: users
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - './:/var/www/html'
        networks:
            - users
        depends_on:
            - mysql

    mysql:
        image: 'mysql:8.0'
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        ports:
            - "3306:3306"
        volumes:
            - 'db_data:/var/lib/mysql'
            - './docker-compose/mysql:/docker-entrypoint-initdb.d'
        networks:
            - users
    
    # pgsql:
    #     image: postgres:15
    #     restart: always
    #     environment:
    #         POSTGRES_DB: users
    #         POSTGRES_USER: laravel
    #         POSTGRES_PASSWORD: postgres
    #         POSTGRES_ROOT_PASSWORD: postgres
    #     ports:
    #         - "5432:5432"
    #     networks:
    #         - users
    #     volumes:
    #         - db_data:/var/lib/postgresql/data

volumes:
    db_data:
